apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: my-django-unit:latest
        imagePullPolicy: Never
        command: ["python", "manage.py", "migrate", "--noinput"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: secret-key
        - name: DEBUG
          value: "True"
        - name: ALLOWED_HOSTS
          value: "*"
      restartPolicy: Never
  backoffLimit: 2