apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: clearsessions
            image: my-django-unit:latest
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: database-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: secret-key
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "star-burger.test"